apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: 833178069885.dkr.ecr.us-east-1.amazonaws.com/assignment2:app_v0.2
        ports:
        - containerPort: 8080
        env:
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: mysql-serv.db-namespace.svc.cluster.local
        - name: DBUSER
          value: root
        - name: DATABASE
          value: employees
        - name: DBPWD
          value: pw
        - name: APP_COLOR
          value: cyan
